version: "3"
services:
  squid-alpine:
    image: alpine:3.2
    ports:
      - "8080:8080"
    volumes:
      - ./log:/var/log/
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./cache:/var/cache
    restart: always
